# Generated by Django 6.1 on 2026-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_trekevent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekevent',
            name='date',
            field=models.DateField(),
        ),
    ]
