# Generated by Django 6.1 on 2026-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='max_participants',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
