# Generated by Django 6.1 on 2026-08-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0005_trek_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trek_images/')),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treks.trek')),
            ],
        ),
    ]
