# Generated by Django 6.1 on 2026-08-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0006_trekimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trekevent',
            old_name='location',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='trekevent',
            name='image',
        ),
        migrations.CreateModel(
            name='TrekEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treks.trekevent')),
            ],
        ),
    ]
